### ISSUE TITLE
Update readme to include usage with <script setup>

### ISSUE THREAD

**Issue by CabbagePenetrator** [mahdikhashan/vue3-click-outside#1]
When using the <script setup> syntax I needed to import the library like this to get it to work:
````
import { clickOutSide as vClickOutSide } from '@mahdikhashan/vue3-click-outside'
````

I think the library should mention to do this if you're using the setup syntax.

**Comment by mahdikhashan** [comment]
Thanks for reporting the issue, I'll update the README regarding the usage of library with the composition api.

**Comment by hassanpdn** [comment]
@mahdikhashan How did you use that inside your component?

**Comment by mahdikhashan** [comment]
@hassanpdn I try to add an example to the project later tomorrow. stay tuned.

**Comment by hassanpdn** [comment]
@mahdikhashan okey, I'm waiting for that.
